language: php

sudo: false

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - travis_retry composer global require bayardev/composer-version:TRAVIS_BRANCH
  - travis_retry rm -rf ~/.composer/vendor/bayardev/*
  - travis_retry ln -s $PWD ~/.composer/vendor/bayardev
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - composer test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  slack: bayard-web:VU1TQuHRTQAJj1PSFGx79S4J
